### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by einarpersson** [ludwigsjoberg/snake#3]
Hej! Du har följt en tutorial ganska nära när du gjort denna va? Ange gärna källan i en kommentar längst upp. Ok?

Ps. Tutorials är jättebra för att komma igång men det finns en stor risk i att bara följa tutorials och inte utforska/bygga på egen hand. Det bästa är att mixa. Vad skulle kunna vara ett bra nästa steg för att utmana dig själv, tycker du?

**Comment by ludwigsjoberg** [comment]
Jag kan skriva källan men jag är inte säker på andra sätt jag kan lära mig.
